
name: Tests / E2E Upgrade
on: 
  workflow_dispatch:
    inputs:
      old-tag:
        description: 'The tag before upgrade'
        required: true
        type: string
      new-tag:
        description: 'The tag after upgrade'
        required: true
        type: string
      upgrade-name:
        description: 'The name of upgrade'
        required: true
        type: string
  push:

env:
   REGISTRY: ghcr.io
   ORG: bandprotocol
   IMAGE_NAME: chain
  #  GIT_TAG: "${{ inputs.old-tag }}"
   OLD_TAG: "v2.4.1"
   NEW_TAG: "patch-ibc-v4"
   UPGRADE_NAME: "v2_5"

jobs:
  build-old-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ env.OLD_TAG }}"
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build . -t "${REGISTRY}/${ORG}/${IMAGE_NAME}:${OLD_TAG}"
          docker push "${REGISTRY}/${ORG}/${IMAGE_NAME}:${OLD_TAG}"

  build-new-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ env.NEW_TAG }}"
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build . -t "${REGISTRY}/${ORG}/${IMAGE_NAME}:${NEW_TAG}"
          docker push "${REGISTRY}/${ORG}/${IMAGE_NAME}:${NEW_TAG}"

  test-upgrade:
    needs: [build-original-docker, build-upgraded-docker]
    uses: cosmos/ibc-go/.github/workflows/e2e-test-workflow-call.yml@main
    with:
      chain-image: ghcr.io/bandprotocol/chain
      chain-binary: bandd
      chain-a-tag: ${{ env.OLD_TAG }}
      chain-b-tag: ${{ env.OLD_TAG }}
      chain-upgrade-tag: ${{ env.NEW_TAG }}
      upgrade-plan-name: ${{ env.UPGRADE_NAME }}
      test-entry-point:  "TestUpgradeTestSuite"
      test: "TestIBCChainUpgrade"
